### ISSUE TITLE
How can I manage roles?

### ISSUE THREAD

**Issue by hernanfila** [barseghyanartur/django-fobi#203]
Hi @barseghyanartur , I have one question. I don't want to bother you but maybe you could give me a hint.
How can I force authenticated users only to view incidents? And not to edit them ( or even create forms).
Should I modify fobi code ? 
I tried to read django documentation but I feel that to be able to do this I should modify Fobi code.

Thank you very much

Hernan

**Comment by barseghyanartur** [comment]
@hernanfila:

Only you as the author of the form shall be able to edit the form.
Fobi is written in such a way, that authenticated users can create forms.
However, you don't need to modify entire fobi code to forbid them from creating forms.
You could instead make a local package called `fobi_addons` and place your `create` view there (that one you should copy from fobi). Then in URLs you shall provide the URL to your customised `create` view prior including fobi views.

**Comment by hernanfila** [comment]
@barseghyanartur we have 1 form. We need the users to log in to access the form. Finally, we need to have 2 roles to access our form.

Roles:

- Admin: Full access to django fobi / django
- User: Has only view access (not editing/create/delete) to the form page we created

Form is already created and we can authenticate users with AD without problems. Now, the questions are:

- We want to share the form URL with the users. When they click, we want them to login first and finally being redirected to our form. How can we achieve this?
- Is possible to have these 2 roles above? If so, how can we make them?


With this two questions we think we will have most of our requirements achieved, and finally use Fobi.

Thank you!!

**Comment by barseghyanartur** [comment]
@hernanfila:

I'm not sure what the issue is. What you describe is standard fobi functionality. If you want a form to be only available for authenicated user, you mark it as non public (the `public` checkbox shall be unchecked).

**Comment by hernanfila** [comment]
These are steps I performed: 
1) I made the form non-public.
2) I tried to access the form URL (being logged out). I got an Http 404 error:
![image](https://user-images.githubusercontent.com/1685461/48423433-5af8a280-e73f-11e8-9a20-614ae23ca086.png)

It doesn't redirect me to the authentication page.

Thank you.

**Comment by barseghyanartur** [comment]
@hernanfila:

Yep. No redirect is returned. Just 404. You might want to changed it in your version (as I said, in `fobi_addons`) and return redirect to authentication page instead.

**Comment by hernanfila** [comment]
Steps I have done:
1) Added this to urls.py:

```
from .myAddons import views

urlpatterns = [
    url(r'^fobi/view/', views.view_form_entry),
```

2) Then in myAddons/views.py I added practically the same code than "fobi/views.py".
When I enter to http://172.20.245.66:8000/fobi/view/myForm/ I get the following error:


Traceback:
```
Internal Server Error: /fobi/view/myForm/
Traceback (most recent call last):
  File "/home/myUser/myEnvironments/my_django_env/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/myUser/myEnvironments/my_django_env/lib64/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/myUser/myEnvironments/my_django_env/lib64/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: view_form_entry() missing 1 required positional argument: 'form_entry_slug'
```

If I am able to solve this error, next steps would be:
3) Replace response "error 404" by a redirection to user login, is it OK? 
If you want to add any advises, I am happy to hear.

Thank you so much for your help.

**Comment by barseghyanartur** [comment]
@hernanfila:

Solved?

**Comment by hernanfila** [comment]
Instead of replacing the error to the redirection, I put the decorator "login_required" above view_form_entry function. 
It worked. 
Thank you!
