### ISSUE TITLE
'fobi.contrib.plugins.form_handlers.db_store.view_saved_form_wizard_data_entries' is not a valid view function or pattern name.

### ISSUE THREAD

**Issue by demslob** [barseghyanartur/django-fobi#206]
Python: 3.4
Django: 2.0.6

#############################################################
Full error: 

Internal Server Error: /forms/fobi/wizard/edit/2/
 Traceback (most recent call last):
   File "/usr/lib64/python3.4/site-packages/django/core/handlers/exception.py", line 35, in inner
     response = get_response(request)
   File "/usr/lib64/python3.4/site-packages/django/core/handlers/base.py", line 128, in _get_response
     response = self.process_exception_by_middleware(e, request)
   File "/usr/lib64/python3.4/site-packages/django/core/handlers/base.py", line 126, in _get_response
     response = wrapped_callback(request, *callback_args, **callback_kwargs)
   File "/usr/lib64/python3.4/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
     return view_func(request, *args, **kwargs)
   File "/usr/lib64/python3.4/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
     return view_func(request, *args, **kwargs)
   File "/usr/lib/python3.4/site-packages/fobi/views.py", line 1381, in edit_form_wizard_entry
     return render(request, template_name, context)
   File "/usr/lib64/python3.4/site-packages/django/shortcuts.py", line 36, in render
     content = loader.render_to_string(template_name, context, request, using=using)
   File "/usr/lib64/python3.4/site-packages/django/template/loader.py", line 62, in render_to_string
     return template.render(context, request)
   File "/usr/lib64/python3.4/site-packages/django/template/backends/django.py", line 61, in render
     return self.template.render(context)
   File "/usr/lib64/python3.4/site-packages/django/template/base.py", line 175, in render
     return self._render(context)
   File "/usr/lib64/python3.4/site-packages/django/template/base.py", line 167, in _render
     return self.nodelist.render(context)
   File "/usr/lib64/python3.4/site-packages/django/template/base.py", line 943, in render
     bit = node.render_annotated(context)
   File "/usr/lib64/python3.4/site-packages/django/template/base.py", line 910, in render_annotated
     return self.render(context)
   File "/usr/lib64/python3.4/site-packages/django/template/loader_tags.py", line 155, in render
     return compiled_parent._render(context)
   File "/usr/lib64/python3.4/site-packages/django/template/base.py", line 167, in _render
     return self.nodelist.render(context)
   File "/usr/lib64/python3.4/site-packages/django/template/base.py", line 943, in render
     bit = node.render_annotated(context)
   File "/usr/lib64/python3.4/site-packages/django/template/base.py", line 910, in render_annotated
     return self.render(context)
   File "/usr/lib64/python3.4/site-packages/django/template/loader_tags.py", line 155, in render
     return compiled_parent._render(context)
   File "/usr/lib64/python3.4/site-packages/django/template/base.py", line 167, in _render
     return self.nodelist.render(context)
   File "/usr/lib64/python3.4/site-packages/django/template/base.py", line 943, in render
     bit = node.render_annotated(context)
   File "/usr/lib64/python3.4/site-packages/django/template/base.py", line 910, in render_annotated
     return self.render(context)
   File "/usr/lib64/python3.4/site-packages/django/template/loader_tags.py", line 155, in render
     return compiled_parent._render(context)
   File "/usr/lib64/python3.4/site-packages/django/template/base.py", line 167, in _render
     return self.nodelist.render(context)
   File "/usr/lib64/python3.4/site-packages/django/template/base.py", line 943, in render
     bit = node.render_annotated(context)
   File "/usr/lib64/python3.4/site-packages/django/template/base.py", line 910, in render_annotated
     return self.render(context)
   File "/usr/lib64/python3.4/site-packages/django/template/loader_tags.py", line 155, in render
     return compiled_parent._render(context)
   File "/usr/lib64/python3.4/site-packages/django/template/base.py", line 167, in _render
     return self.nodelist.render(context)
   File "/usr/lib64/python3.4/site-packages/django/template/base.py", line 943, in render
     bit = node.render_annotated(context)
   File "/usr/lib64/python3.4/site-packages/django/template/base.py", line 910, in render_annotated
     return self.render(context)
   File "/usr/lib64/python3.4/site-packages/django/template/loader_tags.py", line 67, in render
     result = block.nodelist.render(context)
   File "/usr/lib64/python3.4/site-packages/django/template/base.py", line 943, in render
     bit = node.render_annotated(context)
   File "/usr/lib64/python3.4/site-packages/django/template/base.py", line 910, in render_annotated
     return self.render(context)
   File "/usr/lib64/python3.4/site-packages/django/template/loader_tags.py", line 67, in render
     result = block.nodelist.render(context)
   File "/usr/lib64/python3.4/site-packages/django/template/base.py", line 943, in render
     bit = node.render_annotated(context)
   File "/usr/lib64/python3.4/site-packages/django/template/base.py", line 910, in render_annotated
     return self.render(context)
   File "/usr/lib64/python3.4/site-packages/django/template/loader_tags.py", line 67, in render
     result = block.nodelist.render(context)
   File "/usr/lib64/python3.4/site-packages/django/template/base.py", line 943, in render
     bit = node.render_annotated(context)
   File "/usr/lib64/python3.4/site-packages/django/template/base.py", line 910, in render_annotated
     return self.render(context)
   File "/usr/lib64/python3.4/site-packages/django/template/loader_tags.py", line 67, in render
     result = block.nodelist.render(context)
   File "/usr/lib64/python3.4/site-packages/django/template/base.py", line 943, in render
     bit = node.render_annotated(context)
   File "/usr/lib64/python3.4/site-packages/django/template/base.py", line 910, in render_annotated
     return self.render(context)
   File "/usr/lib64/python3.4/site-packages/django/template/loader_tags.py", line 194, in render
     return template.render(context)
   File "/usr/lib64/python3.4/site-packages/django/template/base.py", line 177, in render
     return self._render(context)
   File "/usr/lib64/python3.4/site-packages/django/template/base.py", line 167, in _render
     return self.nodelist.render(context)
   File "/usr/lib64/python3.4/site-packages/django/template/base.py", line 943, in render
     bit = node.render_annotated(context)
   File "/usr/lib64/python3.4/site-packages/django/template/base.py", line 910, in render_annotated
     return self.render(context)
   File "/usr/lib64/python3.4/site-packages/django/template/loader_tags.py", line 155, in render
     return compiled_parent._render(context)
   File "/usr/lib64/python3.4/site-packages/django/template/base.py", line 167, in _render
     return self.nodelist.render(context)
   File "/usr/lib64/python3.4/site-packages/django/template/base.py", line 943, in render
     bit = node.render_annotated(context)
   File "/usr/lib64/python3.4/site-packages/django/template/base.py", line 910, in render_annotated
     return self.render(context)
   File "/usr/lib64/python3.4/site-packages/django/template/defaulttags.py", line 314, in render
     return nodelist.render(context)
   File "/usr/lib64/python3.4/site-packages/django/template/base.py", line 943, in render
     bit = node.render_annotated(context)
   File "/usr/lib64/python3.4/site-packages/django/template/base.py", line 910, in render_annotated
     return self.render(context)
   File "/usr/lib64/python3.4/site-packages/django/template/defaulttags.py", line 211, in render
     nodelist.append(node.render_annotated(context))
   File "/usr/lib64/python3.4/site-packages/django/template/base.py", line 910, in render_annotated
     return self.render(context)
   File "/usr/lib64/python3.4/site-packages/django/template/defaulttags.py", line 517, in render
     return self.nodelist.render(context)
   File "/usr/lib64/python3.4/site-packages/django/template/base.py", line 943, in render
     bit = node.render_annotated(context)
   File "/usr/lib64/python3.4/site-packages/django/template/base.py", line 910, in render_annotated
     return self.render(context)
   File "/usr/lib64/python3.4/site-packages/django/template/defaulttags.py", line 314, in render
     return nodelist.render(context)
   File "/usr/lib64/python3.4/site-packages/django/template/base.py", line 943, in render
     bit = node.render_annotated(context)
   File "/usr/lib64/python3.4/site-packages/django/template/base.py", line 910, in render_annotated
     return self.render(context)
   File "/usr/lib/python3.4/site-packages/fobi/templatetags/fobi_tags.py", line 187, in render
     request)
   File "/usr/lib/python3.4/site-packages/fobi/base.py", line 1986, in get_custom_actions
     return self.custom_actions(form_wizard_entry, request)
   File "/usr/lib/python3.4/site-packages/fobi/contrib/plugins/form_handlers/db_store/base.py", line 209, in custom_actions
     args=[form_wizard_entry.pk]),
   File "/usr/lib64/python3.4/site-packages/django/urls/base.py", line 90, in reverse
     return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
   File "/usr/lib64/python3.4/site-packages/django/urls/resolvers.py", line 636, in _reverse_with_prefix
     raise NoReverseMatch(msg)
 django.urls.exceptions.NoReverseMatch: Reverse for 'fobi.contrib.plugins.form_handlers.db_store.view_saved_form_wizard_data_entries' not found. 'fobi.contrib.plugins.form_handlers.db_store.view_saved_form_wizard_data_entries' is not a valid view function or pattern name.

**Comment by demslob** [comment]
It happens when DB handler is used in form or form wizard.

**Comment by barseghyanartur** [comment]
@demslob:

Which fobi version are you using?

**Comment by barseghyanartur** [comment]
@demslob:

It works in the demo.

http://django-fobi.herokuapp.com/en/fobi/plugins/form-wizard-handlers/db-store/252/

@hernanfila:

[Demo](http://django-fobi.herokuapp.com/en/fobi/) is currently running on `Python` 3.6, `Django` 2.1 and `django-fobi` == 0.13.5.

The full list of demo requirements:

```
bleach==1.5.0
Django>=2.1,<2.2
SQLAlchemy==0.9.8
dj-database-url==0.5.0
django-postgrespool==0.3.1
gunicorn==19.9.0
psycopg2==2.7.5
whitenoise==4.0
ipython

MarkupSafe
django-fobi==0.13.5
django-admin-tools>=0.8.1
django-autoslug-iplweb
django-ckeditor>=5.6.0
https://github.com/marbont/django-codemirror-widget/archive/12bb692f805c47e5d418ae26be7e190f7138f364.zip
django-formtools>=2.1
django-nine>=0.1.10
django-nonefield>=0.3
django-registration-redux>=2.4
easy-thumbnails>=2.5.0
ordereddict>=1.1
simple-timer>=0.2
vishap>=0.1.5

django-simple-captcha>=0.5.7
mailchimp

django-admin-timeline>=1.6.1

FeinCMS==1.13.6
django-mptt==0.9.1

djangorestframework==3.8.2
```

Additionally, see the [example requirements for Django 2.1](https://github.com/barseghyanartur/django-fobi/blob/master/examples/requirements/django_2_1.txt).

I'll check the Django 2.0 wizards asap. In any case, please, tell me which version of `django-fobi` do you experience it with.

**Comment by demslob** [comment]
@barseghyanartur 

Python  3.4 and django-fobi 0.13.8

The full list of my project libs:
amqp==2.4.1
asn1crypto==0.24.0
billiard==3.5.0.5
bleach==3.1.0
celery==4.2.1
certifi==2018.11.29
cffi==1.12.1
chardet==3.0.4
cryptography==2.5
Django==2.0
django-autoslug-iplweb==1.9.4
django-celery-beat==1.1.1
django-fobi==0.13.8
django-formtools==2.1
django-nine==0.1.13
django-nonefield==0.3
django-ratelimit==2.0.0
django-redis==4.10.0
djangorestframework==3.9.1
easy-thumbnails==2.6
future==0.17.1
idna==2.8
kombu==4.3.0
mysqlclient==1.3.10
Pillow==5.4.1
pycparser==2.19
python-telegram-bot==11.1.0
pytz==2018.9
redis==2.10.6
requests==2.21.0
simplejson==3.16.0
six==1.12.0
Unidecode==1.0.23
urllib3==1.24.1
uWSGI==2.0.17
vine==1.2.0
vishap==0.1.5
webencodings==0.5.1
xlwt==1.3.0

**Comment by barseghyanartur** [comment]
@demslob:

You should have forgotten to add the views to the `urls.py`.

See an [https://github.com/barseghyanartur/django-fobi/blob/master/examples/simple/urls.py#L37](example).

It's also mentioned in the [docs](https://django-fobi.readthedocs.io/en/latest/index.html#installation) and dedicated [plugin docs](https://github.com/barseghyanartur/django-fobi/tree/master/src/fobi/contrib/plugins/form_handlers/db_store).

Since you're new to fobi, please, make sure you have read the docs before raising your questions here.
