### ISSUE TITLE
Form export broken with `simplejson-3.16.0`

### ISSUE THREAD

**Issue by freezed** [barseghyanartur/django-fobi#217]
Traceback (french translated ULRs) :
```
[24/Apr/2019 14:29:10] "GET /fobi/dashboard/formulaires/modifier/1/?active_tab=tab-form-handlers HTTP/1.1" 200 34135
Internal Server Error: /fobi/dashboard/formulaires/exporter/1/
Traceback (most recent call last):
  File "~/git/repo/.venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner                
    response = get_response(request)
  File "~/git/repo/.venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response            
    response = self.process_exception_by_middleware(e, request)                                                                            
  File "~/git/repo/.venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response            
    response = wrapped_callback(request, *callback_args, **callback_kwargs)                                                                
  File "~/git/repo/.venv/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view        
    return view_func(request, *args, **kwargs)                                                                                             
  File "~/git/repo/.venv/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view        
    return view_func(request, *args, **kwargs)                                                                                             
  File "~/git/repo/.venv/lib/python3.6/site-packages/fobi/views/function_based.py", line 2129, in export_form_entry       
    json.dumps(data, cls=DjangoJSONEncoder),
  File "~/git/repo/.venv/lib/python3.6/site-packages/simplejson/__init__.py", line 399, in dumps                          
    **kw).encode(obj)
TypeError: __init__() got an unexpected keyword argument 'encoding'
[24/Apr/2019 14:29:21] "GET /fobi/dashboard/formulaires/exporter/1/ HTTP/1.1" 500 104373
```

`pip freeze` : 
```
bleach==3.1.0
certifi==2019.3.9
chardet==3.0.4
Django==2.2
django-autoslug-iplweb==1.9.4
django-fobi==0.13.10
django-formtools==2.1
django-nine==0.1.13
django-nonefield==0.3
easy-thumbnails==2.6
idna==2.8
Pillow==6.0.0
pkg-resources==0.0.0
pytz==2019.1
requests==2.21.0
simplejson==3.16.0
six==1.12.0
sqlparse==0.3.0
Unidecode==1.0.23
urllib3==1.24.2
vishap==0.1.5
webencodings==0.5.1
```
Fixed with rolling back to `simplejson==3.8.0`

**Comment by barseghyanartur** [comment]
@freezed:

So, let's pin it to 3.8.0.

Additionally, at some point there's a need to switch back to `django-autoslug`, since that one is alive again and `django-autoslug-iplweb` can be removed.

**Comment by barseghyanartur** [comment]
@freezed:

WIP in branch [wipe-lt-1-8](https://github.com/barseghyanartur/django-fobi/tree/wipe-lt-1-8).

**Comment by barseghyanartur** [comment]
Done in 0.14.
