### ISSUE TITLE
Fobi not working with custom user model | Django 1.9

### ISSUE THREAD

**Issue by geekashu** [barseghyanartur/django-fobi#27]
I am using custom user model on django 1.9 and not able to get this package working. Following is the stack trace.

```
  File "/home/ashish/Env/backend/lib/python3.4/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/ashish/Env/backend/lib/python3.4/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/home/ashish/Env/backend/lib/python3.4/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/home/ashish/Env/backend/lib/python3.4/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/ashish/Env/backend/lib/python3.4/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/ashish/Env/backend/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/ashish/Env/backend/lib/python3.4/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/ashish/Env/backend/lib/python3.4/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/ashish/Env/backend/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/ashish/Env/backend/lib/python3.4/site-packages/fobi/models.py", line 27, in <module>
    from fobi.base import (
  File "/home/ashish/Env/backend/lib/python3.4/site-packages/fobi/base.py", line 76, in <module>
    from fobi.helpers import (
  File "/home/ashish/Env/backend/lib/python3.4/site-packages/fobi/helpers.py", line 46, in <module>
    from nine.user import User
  File "/home/ashish/Env/backend/lib/python3.4/site-packages/nine/user.py", line 34, in <module>
    User = apps.get_registered_model(user_app_name, user_model_name)
  File "/home/ashish/Env/backend/lib/python3.4/site-packages/django/apps/registry.py", line 260, in get_registered_model
    "Model '%s.%s' not registered." % (app_label, model_name))
LookupError: Model 'users.User' not registered.
```

**Comment by barseghyanartur** [comment]
@geekashu:

It used to work well with [custom user model](https://github.com/barseghyanartur/django-fobi/blob/master/examples/simple/settings_custom_user_model.py). Thanks for reporting this. I'll check it ASAP.

**Comment by geekashu** [comment]
Would appreciate if you could point me in right direction to look for the fix. I want to use this package in my django app.

Also how can i use django rest framework to get the form using REST API which then can be consumed by angular based frontend app to render it to intendend users?

**Comment by barseghyanartur** [comment]
@geekashu:

Do you mean that you would want to define the form using standard django-fobi interface (see the demo online) and then make all the forms available via some `django-rest-framework` (OPTIONS and POST)? Not a bad idea, but that's not implemented.

**Comment by geekashu** [comment]
Yup, That is correct.

**Comment by geekashu** [comment]
Hi... I had to put fobi app below my custom user app in settings.. that solved the issue. 

Now i am getting following stack trace while trying to view the created form in django admin. I have properly defined the urls in urls.py file and performed the migrations and fobi_sync_plugins.
```
# View URLs
url(r'^fobi/', include('fobi.urls.view')),

# Edit URLs
url(r'^fobi/', include('fobi.urls.edit')),
```



```
Traceback (most recent call last):
  File "/home/ashish/Env/backend/lib/python3.4/site-packages/django/core/handlers/base.py", line 174, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ashish/Env/backend/lib/python3.4/site-packages/django/core/handlers/base.py", line 172, in get_response
    response = response.render()
  File "/home/ashish/Env/backend/lib/python3.4/site-packages/django/template/response.py", line 160, in render
    self.content = self.rendered_content
  File "/home/ashish/Env/backend/lib/python3.4/site-packages/django/template/response.py", line 137, in rendered_content
    content = template.render(context, self._request)
  File "/home/ashish/Env/backend/lib/python3.4/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/home/ashish/Env/backend/lib/python3.4/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/home/ashish/Env/backend/lib/python3.4/site-packages/django/test/utils.py", line 92, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/ashish/Env/backend/lib/python3.4/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/ashish/Env/backend/lib/python3.4/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/ashish/Env/backend/lib/python3.4/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/home/ashish/Env/backend/lib/python3.4/site-packages/django/test/utils.py", line 92, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/ashish/Env/backend/lib/python3.4/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/ashish/Env/backend/lib/python3.4/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/ashish/Env/backend/lib/python3.4/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/home/ashish/Env/backend/lib/python3.4/site-packages/django/test/utils.py", line 92, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/ashish/Env/backend/lib/python3.4/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/ashish/Env/backend/lib/python3.4/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/ashish/Env/backend/lib/python3.4/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/home/ashish/Env/backend/lib/python3.4/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/ashish/Env/backend/lib/python3.4/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/ashish/Env/backend/lib/python3.4/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/home/ashish/Env/backend/lib/python3.4/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/ashish/Env/backend/lib/python3.4/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/ashish/Env/backend/lib/python3.4/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/home/ashish/Env/backend/lib/python3.4/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/ashish/Env/backend/lib/python3.4/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/ashish/Env/backend/lib/python3.4/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/home/ashish/Env/backend/lib/python3.4/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/ashish/Env/backend/lib/python3.4/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/ashish/Env/backend/lib/python3.4/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
  File "/home/ashish/Env/backend/lib/python3.4/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/ashish/Env/backend/lib/python3.4/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/ashish/Env/backend/lib/python3.4/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
  File "/home/ashish/Env/backend/lib/python3.4/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/ashish/Env/backend/lib/python3.4/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/ashish/Env/backend/lib/python3.4/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/home/ashish/Env/backend/lib/python3.4/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/ashish/Env/backend/lib/python3.4/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/ashish/Env/backend/lib/python3.4/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
  File "/home/ashish/Env/backend/lib/python3.4/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/ashish/Env/backend/lib/python3.4/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/ashish/Env/backend/lib/python3.4/site-packages/django/template/base.py", line 1043, in render
    output = self.filter_expression.resolve(context)
  File "/home/ashish/Env/backend/lib/python3.4/site-packages/django/template/base.py", line 709, in resolve
    obj = self.var.resolve(context)
  File "/home/ashish/Env/backend/lib/python3.4/site-packages/django/template/base.py", line 850, in resolve
    value = self._resolve_lookup(context)
  File "/home/ashish/Env/backend/lib/python3.4/site-packages/django/template/base.py", line 913, in _resolve_lookup
    current = current()
  File "/home/ashish/Env/backend/lib/python3.4/site-packages/fobi/models.py", line 313, in get_absolute_url
    return reverse('fobi.form_entry', kwargs={'slug': self.slug})
  File "/home/ashish/Env/backend/lib/python3.4/site-packages/django/core/urlresolvers.py", line 600, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/home/ashish/Env/backend/lib/python3.4/site-packages/django/core/urlresolvers.py", line 508, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
django.core.urlresolvers.NoReverseMatch: Reverse for 'fobi.form_entry' with arguments '()' and keyword arguments '{'slug': 'test-form'}' not found. 0 pattern(s) tried: []
```

**Comment by geekashu** [comment]
I made some changes in `def get_absolute_url(self):` to get it working... I am using django suit and it had some issues [Django Suit Issue - #331](https://github.com/darklow/django-suit/issues/331#issuecomment-68859890)

from 
`return reverse('fobi.form_entry', kwargs={'slug': self.slug})`
to
`return reverse('fobi.view_form_entry', kwargs={'form_entry_slug': self.slug})`

**Comment by barseghyanartur** [comment]
@geekashu:

FYI, `django-rest-framework` integration has been added to the TODOs and will be impemented in the nearest future.

**Comment by geekashu** [comment]
Thank you... Much appreciated

**Comment by nicolasmendoza** [comment]
@barseghyanartur  I'm having this same error in Django 2.0.
**"LookupError: Model 'accounts.Account' not registered."**

 The workaround of appending to "installed_app" the "custom app" doesn't works. Can you provide more information ?, Maybe I can solve this and send a PR. 
This bug cause instability in our deployments because the runserver works/up sometimes but  sometimes doesn't works getting this error message of fobi.  Is very very strange, is as lotery, sometimes works sometimes not, sometimes need reboot the runserver.

Please help me or provide me more information, and I can work to solve this and send a Pull request.

Thanks.

**Comment by barseghyanartur** [comment]
@nicolasmendoza:

In past I had it working with:

- https://github.com/barseghyanartur/django-fobi/blob/master/examples/simple/settings/custom_user_model.py

I'll check it if it still works (it should).

Please, confirm that it does not work for you with these settings.

**Comment by hcNick** [comment]
@barseghyanartur I notice you're using your own compatibility library, any reason you aren't using django.contrib.admin.get_user_model()? I made an older version of django-fobi custom user model compatible using these fixes https://github.com/HiddenClever/django-fobi/commit/c9c3bd9961bb5dfc710cb61547e13fd22a4852b4 https://github.com/HiddenClever/django-fobi/commit/b070ff368bdccef89323fde128b88ef7e6e0085b

**Comment by barseghyanartur** [comment]
Could you come up with a patch?

**Comment by nicolasmendoza** [comment]
Hi, this is working fine. I'm Sorry for the delay. 
The inconvenient was caused for a third library not related with fobi.
THanks-

**Comment by barseghyanartur** [comment]
You're welcome and thanks for the update.
