### ISSUE TITLE
ThemeDoesNotExist: Theme `bootstrap3` does not exist!

### ISSUE THREAD

**Issue by philgyford** [barseghyanartur/django-fobi#76]
I'm setting fobi up for the first time. I've followed the Quick Start instructions. Python 2.7, Django 1.11.3.

My `INSTALLED_APPS` include these fobi apps:

    'fobi',
    'fobi.contrib.themes.simple',
    'fobi.contrib.plugins.form_elements.fields.boolean',
    'fobi.contrib.plugins.form_elements.fields.checkbox_select_multiple',
    'fobi.contrib.plugins.form_elements.fields.text',

My `TEMPLATES` looks like:

    TEMPLATES = [
        {
            'BACKEND': 'django.template.backends.jinja2.Jinja2',
            'APP_DIRS': True,
            'OPTIONS': {
                'context_processors': (
                    'django.template.context_processors.debug',
                    'django.template.context_processors.request',
                    'django.contrib.auth.context_processors.auth',
                    'django.contrib.messages.context_processors.messages',
                    'fobi.context_processors.theme',
                ),
                'extensions': [
                    'django_jinja.builtins.extensions.UrlsExtension',
                ],
            },
            'DIRS': [
                os.path.join(BASE_DIR, 'templates'),
            ],
        },
    ]

I've added the fobi URLs to my `urls.py`.

But I get this error when running the dev server or trying to run migrations:

```
Unhandled exception in thread started by <function wrapper at 0x7f6634653140>
Traceback (most recent call last):
  File "/vagrant/venv/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/vagrant/venv/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    autoreload.raise_last_exception()
  File "/vagrant/venv/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 250, in raise_last_exception
    six.reraise(*_exception)
  File "/vagrant/venv/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/vagrant/venv/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/vagrant/venv/local/lib/python2.7/site-packages/django/apps/registry.py", line 116, in populate
    app_config.ready()
  File "/vagrant/venv/local/lib/python2.7/site-packages/django/contrib/admin/apps.py", line 23, in ready
    self.module.autodiscover()
  File "/vagrant/venv/local/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/vagrant/venv/local/lib/python2.7/site-packages/django/utils/module_loading.py", line 50, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/vagrant/venv/local/lib/python2.7/site-packages/fobi/admin.py", line 15, in <module>
    from .forms import (
  File "/vagrant/venv/local/lib/python2.7/site-packages/fobi/forms.py", line 191, in <module>
    class FormElementEntryForm(forms.ModelForm):
  File "/vagrant/venv/local/lib/python2.7/site-packages/fobi/forms.py", line 195, in FormElementEntryForm
    choices=get_registered_form_element_plugins()
  File "/vagrant/venv/local/lib/python2.7/site-packages/fobi/base.py", line 2884, in get_registered_form_element_plugins
    return get_registered_plugins(form_element_plugin_registry)
  File "/vagrant/venv/local/lib/python2.7/site-packages/fobi/base.py", line 2795, in get_registered_plugins
    ensure_autodiscover()
  File "/vagrant/venv/local/lib/python2.7/site-packages/fobi/base.py", line 2742, in ensure_autodiscover
    autodiscover()
  File "/vagrant/venv/local/lib/python2.7/site-packages/fobi/discover.py", line 87, in autodiscover
    autodiscover_modules(FORM_ELEMENT_PLUGINS_MODULE_NAME)
  File "/vagrant/venv/local/lib/python2.7/site-packages/django/utils/module_loading.py", line 50, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/vagrant/venv/local/lib/python2.7/site-packages/fobi/contrib/plugins/form_elements/fields/boolean/fobi_form_elements.py", line 5, in <module>
    from .base import BooleanSelectPlugin
  File "/vagrant/venv/local/lib/python2.7/site-packages/fobi/contrib/plugins/form_elements/fields/boolean/base.py", line 7, in <module>
    from .forms import BooleanSelectForm
  File "/vagrant/venv/local/lib/python2.7/site-packages/fobi/contrib/plugins/form_elements/fields/boolean/forms.py", line 12, in <module>
    theme = get_theme(request=None, as_instance=True)
  File "/vagrant/venv/local/lib/python2.7/site-packages/fobi/base.py", line 3394, in get_theme
    ensure_autodiscover()
  File "/vagrant/venv/local/lib/python2.7/site-packages/fobi/base.py", line 2742, in ensure_autodiscover
    autodiscover()
  File "/vagrant/venv/local/lib/python2.7/site-packages/fobi/discover.py", line 87, in autodiscover
    autodiscover_modules(FORM_ELEMENT_PLUGINS_MODULE_NAME)
  File "/vagrant/venv/local/lib/python2.7/site-packages/django/utils/module_loading.py", line 50, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/vagrant/venv/local/lib/python2.7/site-packages/fobi/contrib/plugins/form_elements/fields/checkbox_select_multiple/fobi_form_elements.py", line 5, in <module>
    from .base import CheckboxSelectMultipleInputPlugin
  File "/vagrant/venv/local/lib/python2.7/site-packages/fobi/contrib/plugins/form_elements/fields/checkbox_select_multiple/base.py", line 10, in <module>
    from .forms import CheckboxSelectMultipleInputForm
  File "/vagrant/venv/local/lib/python2.7/site-packages/fobi/contrib/plugins/form_elements/fields/checkbox_select_multiple/forms.py", line 14, in <module>
    theme = get_theme(request=None, as_instance=True)
  File "/vagrant/venv/local/lib/python2.7/site-packages/fobi/base.py", line 3394, in get_theme
    ensure_autodiscover()
  File "/vagrant/venv/local/lib/python2.7/site-packages/fobi/base.py", line 2742, in ensure_autodiscover
    autodiscover()
  File "/vagrant/venv/local/lib/python2.7/site-packages/fobi/discover.py", line 87, in autodiscover
    autodiscover_modules(FORM_ELEMENT_PLUGINS_MODULE_NAME)
  File "/vagrant/venv/local/lib/python2.7/site-packages/django/utils/module_loading.py", line 50, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/vagrant/venv/local/lib/python2.7/site-packages/fobi/contrib/plugins/form_elements/fields/text/fobi_form_elements.py", line 5, in <module>
    from .base import TextInputPlugin
  File "/vagrant/venv/local/lib/python2.7/site-packages/fobi/contrib/plugins/form_elements/fields/text/base.py", line 10, in <module>
    from .forms import TextInputForm
  File "/vagrant/venv/local/lib/python2.7/site-packages/fobi/contrib/plugins/form_elements/fields/text/forms.py", line 15, in <module>
    theme = get_theme(request=None, as_instance=True)
  File "/vagrant/venv/local/lib/python2.7/site-packages/fobi/base.py", line 3402, in get_theme
    _("Theme `{0}` does not exist!").format(theme_uid)
fobi.exceptions.ThemeDoesNotExist: Theme `bootstrap3` does not exist!
```

If I add `'fobi.contrib.themes.bootstrap3',` to `INSTALLED_APPS` the error disappears, but I didn't notice anything in the docs about this theme being required.

**Comment by philgyford** [comment]
I've subsequently realised one problem was that our site uses Jinja templates, and so I've altered our `TEMPLATES` to be like this:

    TEMPLATES = [
        {
            'BACKEND': 'django.template.backends.jinja2.Jinja2',
            'APP_DIRS': True,
            'OPTIONS': {
                'extensions': [
                    'django_jinja.builtins.extensions.UrlsExtension',
                ],
            },
            'DIRS': [
                os.path.join(BASE_DIR, 'templates'),
            ],
        },
        {
            'BACKEND': 'django.template.backends.django.DjangoTemplates',
            'DIRS': [],
            'APP_DIRS': True,
            'OPTIONS': {
                'context_processors': [
                    'django.template.context_processors.debug',
                    'django.template.context_processors.request',
                    'django.contrib.auth.context_processors.auth',
                    'django.contrib.messages.context_processors.messages',
                    'fobi.context_processors.theme',
                ],
            },
        },
    ]

I can now use Django Admin and the Fobi editing screens just fine. However I still get the same error if I try and remove the `bootstrap3` theme from `INSTALLED_APPS`.

**Comment by barseghyanartur** [comment]
You should specify the UID of the theme you want to use.

https://github.com/barseghyanartur/django-fobi#tuning
https://github.com/barseghyanartur/django-fobi/blob/master/QUICK_START.rst#specify-the-active-theme

As I understand, in your case it's `simple`.

```python
FOBI_DEFAULT_THEME = 'simple'
```

**Comment by philgyford** [comment]
Ugh, I missed that setting, sorry. Thanks for the correction.
